// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCP3TQ80dkHFHA6lViAzYTSWpqTLgEAJUs',
    appId: '1:710796831919:web:ed297afbae5726c0d4785a',
    messagingSenderId: '710796831919',
    projectId: 'employee-ease-b5437',
    authDomain: 'employee-ease-b5437.firebaseapp.com',
    storageBucket: 'employee-ease-b5437.firebasestorage.app',
    measurementId: 'G-F5E9GQB2T6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDhECKo6KLoXyXj60tFAQLl0Z1AgvzM35E',
    appId: '1:710796831919:android:5e984101eac25d02d4785a',
    messagingSenderId: '710796831919',
    projectId: 'employee-ease-b5437',
    storageBucket: 'employee-ease-b5437.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAmlZDdPL9v2IBK0rfDylaWrEvhpzsjzmo',
    appId: '1:710796831919:ios:2f454dce3fe7fce2d4785a',
    messagingSenderId: '710796831919',
    projectId: 'employee-ease-b5437',
    storageBucket: 'employee-ease-b5437.firebasestorage.app',
    iosBundleId: 'com.z.employeeEase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAmlZDdPL9v2IBK0rfDylaWrEvhpzsjzmo',
    appId: '1:710796831919:ios:2f454dce3fe7fce2d4785a',
    messagingSenderId: '710796831919',
    projectId: 'employee-ease-b5437',
    storageBucket: 'employee-ease-b5437.firebasestorage.app',
    iosBundleId: 'com.z.employeeEase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCP3TQ80dkHFHA6lViAzYTSWpqTLgEAJUs',
    appId: '1:710796831919:web:1f4299cd3bcb6a45d4785a',
    messagingSenderId: '710796831919',
    projectId: 'employee-ease-b5437',
    authDomain: 'employee-ease-b5437.firebaseapp.com',
    storageBucket: 'employee-ease-b5437.firebasestorage.app',
    measurementId: 'G-JZW3G23SLP',
  );
}
